In [0]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm


  # graph it
        

In [0]:
DATADIR = '/content/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'

CATEGORIES = [ 'agricultural',  'airplane',    'baseballdiamond', 'beach',   'buildings',          'chaparral',         'denseresidential',
                'forest',        'freeway',     'golfcourse',      'harbor',  'intersection',       'mediumresidential', 'mobilehomepark',
                'overpass',      'parkinglot',  'river',           'runway',  'sparseresidential',  'storagetanks',      'tenniscourt' ]


In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

Using TensorFlow backend.


In [0]:
path = os.path.abspath('.cnn.py')

In [0]:
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file

In [0]:
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')

In [10]:
img_rows = 256
img_cols = 256
num_class = 21
path = os.path.abspath('.cnn.py') #absolute path of program
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file
x_train = []
y_train = []
x_test = []
y_test = []
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')
dirs=dirs[:]
print(len(dirs))
'''

'''

21


'\n\n'

In [0]:
label = 0
for i in dirs:
	n = 0
	count = 0
	for pic in glob.glob(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'+i+'/*.tif'):
		im = Image.open(pic)
		im = np.array(im)
		if((im.shape[0]==256) and (im.shape[1] ==256) and count <90): #get only 90 data
			r = im[:,:,0]
			g = im[:,:,1]
			b = im[:,:,2]
			#if(n<5): # 5 data in beginning set as test data
			#	x_test.append([r,g,b])
			#	y_test.append([label])
			#else: #remaining data set as training data
			x_train.append([r,g,b])
			y_train.append([label])
			n = n + 1
			count = count + 1
		#print(count)
	label = label + 1

In [0]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train.shape
y_train.shape

(1890, 1)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2, random_state = 142)

In [15]:
y_train[0:10]

array([[17],
       [20],
       [18],
       [16],
       [ 8],
       [ 4],
       [ 5],
       [10],
       [16],
       [16]])

In [0]:
from skimage import feature
import numpy as np
 
class LocalBinaryPatterns:
  def __init__(self, numPoints, radius):
# store the number of points and radius
    self.numPoints = numPoints
    self.radius = radius
  def describe(self, image, eps=1e-7):
		# compute the Local Binary Pattern representation
		# of the image, and then use the LBP representation
		# to build the histogram of patterns
    lbp = feature.local_binary_pattern(image, self.numPoints,
    self.radius, method="uniform")
    return lbp 

In [0]:
desc = LocalBinaryPatterns(24, 8)

In [0]:
x_trainbck=X_train
x_testbck=X_test


In [0]:
x_train=np.array(X_train)
x_test=np.array(X_test)

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)

input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)

In [0]:
x_train_lbp=[]


In [0]:
for i in x_train:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_train_lbp.append(hist)

In [0]:
x_train_lbp=np.array(x_train_lbp)

In [24]:
x_train_lbp.shape

(1512, 256, 256)

In [0]:
x_test_lbp=[]

In [0]:
for i in x_test:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_test_lbp.append(hist)

In [0]:
x_test_lbp=np.array(x_test_lbp)

In [28]:
x_test_lbp.shape

(378, 256, 256)

In [0]:
c=[]
for i in range(1512):
  c.append(np.dstack((x_train[i],x_train_lbp[i])))

In [27]:
x_train_mix = np.array(c) 
x_train_mix.shape

(1512, 256, 256, 4)

In [1]:
d=[]
for i in range(378):
  d.append(np.dstack((x_test[i],x_test_lbp[i])))

NameError: ignored

In [0]:
x_test_mix = np.array(d) 
x_test_mix.shape

In [0]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [0]:
x_train_lbp = x_train_lbp.reshape(x_train_mix.shape[0], img_rows, img_cols,1)
x_test_lbp = x_test_lbp.reshape(x_test_mix.shape[0], img_rows, img_cols,1)

input_shape = (img_rows, img_cols,1)

In [31]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=x_train_lbp.shape[1:]))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(21, activation='softmax'))
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [32]:
model.fit(x_train_lbp, y_train, batch_size=50, nb_epoch=100, verbose=1, validation_data=(x_test_lbp, y_test))

Train on 1512 samples, validate on 378 samples
Epoch 1/100
1512/1512 [==============================] - 8s 6ms/sample - loss: 20.1899 - acc: 0.0476 - val_loss: 3.0492 - val_acc: 0.0476
Epoch 2/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 2.9830 - acc: 0.0833 - val_loss: 2.9792 - val_acc: 0.0794
Epoch 3/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 2.6789 - acc: 0.1746 - val_loss: 2.9221 - val_acc: 0.0952
Epoch 4/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 2.0708 - acc: 0.3843 - val_loss: 2.9488 - val_acc: 0.1005
Epoch 5/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 1.3481 - acc: 0.6104 - val_loss: 3.0648 - val_acc: 0.1429
Epoch 6/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 0.8884 - acc: 0.7328 - val_loss: 3.2464 - val_acc: 0.1534
Epoch 7/100
1512/1512 [==============================] - 3s 2ms/sample - loss: 0.6407 - acc: 0.8161 - val_loss: 3.1013 - val_acc: 

In [34]:
loss, acc = model.evaluate(x_test_lbp, y_test, verbose=0)
print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))


Testing loss: 7.3105861673910155, acc: 0.14550264179706573



In [0]:
DATADIR = '/content/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'

CATEGORIES = [ 'agricultural',  'airplane',    'baseballdiamond', 'beach',   'buildings',          'chaparral',         'denseresidential',
                'forest',        'freeway',     'golfcourse',      'harbor',  'intersection',       'mediumresidential', 'mobilehomepark',
                'overpass',      'parkinglot',  'river',           'runway',  'sparseresidential',  'storagetanks',      'tenniscourt' ]


In [0]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Flatten, Dense, Dropout
from keras.preprocessing.image import ImageDataGenerator
import time
IMG_SIZE =256 # Replace with the size of your images
NB_CHANNELS =3 # 3 for RGB images or 1 for grayscale images
BATCH_SIZE = 32# Typical values are 8, 16 or 32
NB_TRAIN_IMG = 1680# Replace with the total number training images
NB_VALID_IMG = 420# Replace with the total number validation images

In [0]:
train_datagen = ImageDataGenerator(
    rotation_range = 40,                  
    width_shift_range = 0.2,                  
    height_shift_range = 0.2,                  
    rescale = 1./255,                  
    shear_range = 0.2,                  
    zoom_range = 0.2,                     
    horizontal_flip = True)
validation_datagen = ImageDataGenerator(rescale = 1./255)
train_generator = train_datagen.flow_from_directory(
    path+'/drive/My Drive/ucmerced/UCMerced_LandUse/output/train',
    target_size=(IMG_SIZE,IMG_SIZE),
    class_mode='categorical',
    batch_size = BATCH_SIZE)
validation_generator = validation_datagen.flow_from_directory(
    path+'/drive/My Drive/ucmerced/UCMerced_LandUse/output/val',
    target_size=(IMG_SIZE,IMG_SIZE),
    class_mode='categorical',
    batch_size = BATCH_SIZE)

Found 1680 images belonging to 21 classes.
Found 420 images belonging to 21 classes.


In [0]:
print(len(train_generator))

53


In [0]:
x_train_final=[]

In [0]:
for i in x_train:
  x_train_final.append(i)

In [0]:
print(len(x_train))

1785


In [0]:
for i in range(1785):
  l=[]
  l=x_train_final[i]
  l.append(x_train_lbp[i])
  x_train_final[i]=l

AttributeError: ignored

In [0]:
x_trainbck1=x_trainbck

In [0]:
x_trainbck1.append(x_train_lbp)

In [0]:
x_trainbck11=np.array(x_trainbck1)

In [0]:
x_trainbck11.shape

(1786,)

In [0]:
xtrain=x_train

In [0]:
xtrainlbp=x_train_lbp

In [0]:
for i in range(1785):
  np.concatenate((xtrain[i] , xtrainlbp[i]))

ValueError: ignored

In [0]:
a=[]

In [0]:
np.dstack((x_train[0], x_train_lbp[0]))

(256, 256, 4)

In [0]:
xtrain.shape

(1785, 256, 256, 3)

In [0]:
x_train=xtrain

In [0]:
for i in range(1785):
  np.dstack((x_train[i], x_train_lbp[i]))

ValueError: ignored

In [0]:
for i in x_train:
  print(x_train.shape)

(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)
(1785, 256, 256, 3)


In [0]:
xtrain1=xtrain

In [0]:
xtrain1.shape

(1785, 256, 256, 3)

In [0]:
xtrain1.shape

(1785, 256, 256, 3)

In [0]:
np.dstack((xtrain1[0],xtrainlbp[0])).shape

(256, 256, 4)

In [0]:
c=np.dstack((xtrain1[0],xtrainlbp[0]))

In [0]:
c.shape

(256, 256, 4)

In [0]:
print(c)

[[[2.70588249e-01 2.43137255e-01 2.15686277e-01 2.50000000e+01]
  [1.45098045e-01 6.27451017e-02 1.17647061e-02 6.00000000e+00]
  [0.00000000e+00 0.00000000e+00 3.92156886e-03 8.00000000e+00]
  ...
  [7.84313772e-03 3.92156877e-02 1.68627456e-01 2.50000000e+01]
  [3.72549027e-01 4.70588237e-01 5.60784340e-01 2.50000000e+01]
  [5.92156887e-01 5.68627477e-01 5.41176498e-01 2.50000000e+01]]

 [[3.56862754e-01 3.29411775e-01 2.39215687e-01 2.50000000e+01]
  [1.25490203e-01 3.13725509e-02 0.00000000e+00 6.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.40000000e+01]
  ...
  [3.92156886e-03 3.92156886e-03 1.17647061e-02 8.00000000e+00]
  [3.13725509e-02 1.05882354e-01 2.86274523e-01 2.50000000e+01]
  [4.90196079e-01 5.64705908e-01 6.31372571e-01 1.00000000e+00]]

 [[3.25490206e-01 2.27450982e-01 1.09803922e-01 7.00000000e+00]
  [4.31372561e-02 7.84313772e-03 3.92156886e-03 8.00000000e+00]
  [0.00000000e+00 3.92156886e-03 1.96078438e-02 8.00000000e+00]
  ...
  [1.96078438e-02 

In [0]:
xtrain1[0].shape

(256, 256, 3)

In [0]:
c=[]

In [0]:
for i in range(1785):
  c.append(np.dstack((x_train[i],x_train_lbp[i])))

In [0]:
d=np.array(c)

In [0]:
d.shape

(1785, 256, 256, 4)

In [0]:
x_train_mix=d

In [0]:
h=[]

In [0]:
for i in range(105):
  h.append(np.dstack((x_test[i],x_test_lbp[i])))

In [0]:
x_test_mix=np.array(h)

In [0]:
x_test_mix.shape

(105, 256, 256, 4)

In [0]:
x_train_mix = x_train_mix.reshape(x_train_mix.shape[0], img_rows, img_cols,4)
x_test_mix = x_test_mix.reshape(x_test_mix.shape[0], img_rows, img_cols,4)

input_shape = (img_rows, img_cols,4)

In [0]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=x_train_mix.shape[1:]))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(21, activation='softmax'))
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [0]:
model.fit(x_train_mix, y_train, batch_size=50, nb_epoch=100, verbose=1, validation_data=(x_test_mix, y_test))

Train on 1785 samples, validate on 105 samples
Epoch 1/100
1785/1785 [==============================] - 18s 10ms/sample - loss: 25.5352 - acc: 0.0420 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 2/100
1785/1785 [==============================] - 10s 6ms/sample - loss: 3.0467 - acc: 0.0420 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 3/100
1785/1785 [==============================] - 9s 5ms/sample - loss: 3.0447 - acc: 0.0431 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 4/100
1785/1785 [==============================] - 9s 5ms/sample - loss: 3.0447 - acc: 0.0437 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 5/100
1785/1785 [==============================] - 8s 5ms/sample - loss: 3.0447 - acc: 0.0459 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 6/100
1785/1785 [==============================] - 9s 5ms/sample - loss: 3.0447 - acc: 0.0437 - val_loss: 3.0445 - val_acc: 0.0476
Epoch 7/100
1785/1785 [==============================] - 9s 5ms/sample - loss: 3.0447 - acc: 0.0459 - val_loss: 3.0445 - val_ac