In [0]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm


  # graph it
        

In [0]:
DATADIR = '/content/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'

CATEGORIES = [ 'agricultural',  'airplane',    'baseballdiamond', 'beach',   'buildings',          'chaparral',         'denseresidential',
                'forest',        'freeway',     'golfcourse',      'harbor',  'intersection',       'mediumresidential', 'mobilehomepark',
                'overpass',      'parkinglot',  'river',           'runway',  'sparseresidential',  'storagetanks',      'tenniscourt' ]


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

Using TensorFlow backend.


In [6]:
!ls

drive  sample_data


In [0]:
path = os.path.abspath('.cnn.py')

In [8]:
print(path)

/content/.cnn.py


In [0]:
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file

In [10]:
print(path)

/content/


In [0]:
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')

In [30]:
img_rows = 256
img_cols = 256
num_class = 21
path = os.path.abspath('.cnn.py') #absolute path of program
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file
x_train = []
y_train = []
x_test = []
y_test = []
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')
dirs=dirs[:-1]
print(len(dirs))
'''

'''

21


"\nlabel = 0\nfor i in dirs:\n\tn = 0\n\tcount = 0\n\tfor pic in glob.glob(path+'UCMerced_LandUse/Images/'+i+'/*.tif'):\n\t\tim = Image.open(pic)\n\t\tim = np.array(im)\n\t\tif((im.shape[0]==256) and (im.shape[1] ==256) and count <90): #get only 90 data\n\t\t\tr = im[:,:,0]\n\t\t\tg = im[:,:,1]\n\t\t\tb = im[:,:,2]\n\t\t\tif(n<5): # 5 data in beginning set as test data\n\t\t\t\tx_test.append([r,g,b])\n\t\t\t\ty_test.append([label])\n\t\t\telse: #remaining data set as training data\n\t\t\t\tx_train.append([r,g,b])\n\t\t\t\ty_train.append([label])\n\t\t\tn = n + 1\n\t\t\tcount = count + 1\n\t\t#print(count)\n\tlabel = label + 1\n"

In [0]:
label = 0
for i in dirs:
	n = 0
	count = 0
	for pic in glob.glob(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'+i+'/*.tif'):
		im = Image.open(pic)
		im = np.array(im)
		if((im.shape[0]==256) and (im.shape[1] ==256) and count <90): #get only 90 data
			r = im[:,:,0]
			g = im[:,:,1]
			b = im[:,:,2]
			if(n<5): # 5 data in beginning set as test data
				x_test.append([r,g,b])
				y_test.append([label])
			else: #remaining data set as training data
				x_train.append([r,g,b])
				y_train.append([label])
			n = n + 1
			count = count + 1
		#print(count)
	label = label + 1

In [0]:
x_trainbck=x_train
x_testbck=x_test


In [0]:
x_train=np.array(x_train)
x_test=np.array(x_test)

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)

input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)

In [36]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y_test[0:10])
print(y_train)

(1785, 256, 256, 3)
(1785, 21)
(105, 256, 256, 3)
(105, 21)
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [0]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(21, activation='softmax'))
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

In [38]:
model.fit(x_train, y_train, batch_size=50, nb_epoch=100, verbose=1, validation_data=(x_test, y_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.





Train on 1785 samples, validate on 105 samples
Epoch 1/100





1785/1785 [==============================] - 15s 9ms/step - loss: 3.9894 - acc: 0.0471 - val_loss: 2.9504 - val_acc: 0.0476
Epoch 2/100
1785/1785 [==============================] - 6s 3ms/step - loss: 2.9220 - acc: 0.0941 - val_loss: 2.8115 - val_acc: 0.1429
Epoch 3/100
1785/1785 [==============================] - 6s 3ms/step - loss: 2.6210 - acc: 0.2207 - val_loss: 2.5581 - val_acc: 0.2857
Epoch 4/100
1785/1785 [==============================] - 6s 3ms/step - loss: 2.1574 - acc: 0.3653 - val_loss: 2.2924 - val_acc: 0.4095
Epoch 5/100
1785/1785 [==============================] - 6s 3ms/step - loss: 1.6425 - acc: 0.5356 - val_loss: 1.8634 - val_acc: 0.5524
Epoch 6/100
1785/1785 [==============================] - 6s 3ms/step - loss: 1.2639 - acc: 0.6263 - val_loss: 2.0218 - val_acc: 0.4476
Epoch 7/100
1785/1785 [==============================] - 6s 3ms/step - loss: 0.9642 - acc: 0.7176 - val_loss: 2.0859 - val_acc: 0.4381

In [40]:
loss, acc = model.evaluate(x_test, y_test, verbose=0)
print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))


Testing loss: 3.565957782382057, acc: 0.47619047846112933

